version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["python", "/app/app.py"]
  
  ngrok:
    image: ngrok/ngrok:latest
    entrypoint: ngrok http app:5000 --host-header=app:5000 --url=${NGROK_SUBDOMAIN}
    env_file:
      - .env
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040
